"""empty message

Revision ID: 09c6526f9671
Revises: 78b94c5dfc5b
Create Date: 2022-05-23 00:22:38.287470

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '09c6526f9671'
down_revision = '78b94c5dfc5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('project_ibfk_1', 'project', type_='foreignkey')
    op.drop_column('project', 'members_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('members_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('project_ibfk_1', 'project', 'members', ['members_id'], ['id'])
    # ### end Alembic commands ###
