"""empty message

Revision ID: 946196bcb284
Revises: 90624b79ea02
Create Date: 2022-05-12 09:49:03.022283

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '946196bcb284'
down_revision = '90624b79ea02'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('profile', 'description',
               existing_type=mysql.VARCHAR(length=250),
               nullable=True)
    op.alter_column('profile', 'rol',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    op.alter_column('profile', 'departamento',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    op.alter_column('profile', 'photo',
               existing_type=mysql.VARCHAR(length=200),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('profile', 'photo',
               existing_type=mysql.VARCHAR(length=200),
               nullable=False)
    op.alter_column('profile', 'departamento',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    op.alter_column('profile', 'rol',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    op.alter_column('profile', 'description',
               existing_type=mysql.VARCHAR(length=250),
               nullable=False)
    # ### end Alembic commands ###
