"""empty message

Revision ID: d1dcf692601e
Revises: 8896d9332e95
Create Date: 2022-05-15 17:05:50.369341

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd1dcf692601e'
down_revision = '8896d9332e95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('rol', sa.Enum('ADMINISTRATOR', 'USER', 'OTHER', name='roles'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('profile', sa.Column('fullname', sa.String(length=150), nullable=False))
    op.add_column('profile', sa.Column('gender', sa.Enum('HOMBRE', 'MUJER', name='gender'), nullable=False))
    op.drop_column('profile', 'name')
    op.drop_column('profile', 'lastname')
    op.drop_column('profile', 'departamento')
    op.add_column('project', sa.Column('due_date', sa.Date(), nullable=True))
    op.add_column('project', sa.Column('start_date', sa.Date(), nullable=True))
    op.drop_column('project', 'goals')
    op.drop_column('project', 'finish_date')
    op.drop_column('project', 'members')
    op.drop_column('project', 'rol')
    op.add_column('subtask', sa.Column('members', sa.Integer(), nullable=True))
    op.add_column('subtask', sa.Column('due_date', sa.Date(), nullable=True))
    op.add_column('subtask', sa.Column('start_date', sa.Date(), nullable=True))
    op.drop_constraint('subtask_ibfk_2', 'subtask', type_='foreignkey')
    op.create_foreign_key(None, 'subtask', 'members', ['members'], ['id'])
    op.drop_column('subtask', 'finish_date')
    op.drop_column('subtask', 'user_id')
    op.add_column('task', sa.Column('description', sa.String(length=250), nullable=True))
    op.add_column('task', sa.Column('check_in', sa.Boolean(), nullable=True))
    op.add_column('task', sa.Column('due_date', sa.Date(), nullable=True))
    op.add_column('task', sa.Column('start_date', sa.Date(), nullable=True))
    op.add_column('task', sa.Column('members', sa.String(length=250), nullable=True))
    op.add_column('task', sa.Column('priority', sa.Enum('HIGHT', 'MEDIUM', 'LOW', name='priority'), nullable=False))
    op.create_foreign_key(None, 'task', 'members', ['members'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.drop_column('task', 'priority')
    op.drop_column('task', 'members')
    op.drop_column('task', 'start_date')
    op.drop_column('task', 'due_date')
    op.drop_column('task', 'check_in')
    op.drop_column('task', 'description')
    op.add_column('subtask', sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('subtask', sa.Column('finish_date', sa.DATE(), nullable=True))
    op.drop_constraint(None, 'subtask', type_='foreignkey')
    op.create_foreign_key('subtask_ibfk_2', 'subtask', 'user', ['user_id'], ['id'])
    op.drop_column('subtask', 'start_date')
    op.drop_column('subtask', 'due_date')
    op.drop_column('subtask', 'members')
    op.add_column('project', sa.Column('rol', mysql.ENUM('ADMINISTRATOR', 'USER', 'OTHER'), nullable=False))
    op.add_column('project', sa.Column('members', mysql.VARCHAR(length=50), nullable=True))
    op.add_column('project', sa.Column('finish_date', sa.DATE(), nullable=True))
    op.add_column('project', sa.Column('goals', mysql.VARCHAR(length=50), nullable=True))
    op.drop_column('project', 'start_date')
    op.drop_column('project', 'due_date')
    op.add_column('profile', sa.Column('departamento', mysql.VARCHAR(length=50), nullable=True))
    op.add_column('profile', sa.Column('lastname', mysql.VARCHAR(length=50), nullable=False))
    op.add_column('profile', sa.Column('name', mysql.VARCHAR(length=50), nullable=False))
    op.drop_column('profile', 'gender')
    op.drop_column('profile', 'fullname')
    op.drop_table('members')
    # ### end Alembic commands ###
