"""empty message

Revision ID: dc6b7f3c0b7e
Revises: 715cff955587
Create Date: 2022-05-12 17:32:11.417195

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'dc6b7f3c0b7e'
down_revision = '715cff955587'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('profile', 'description',
               existing_type=mysql.VARCHAR(length=250),
               nullable=True)
    op.alter_column('profile', 'rol',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    op.alter_column('profile', 'departamento',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    op.alter_column('profile', 'photo',
               existing_type=mysql.VARCHAR(length=200),
               nullable=True)
    op.alter_column('project', 'members',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    op.alter_column('project', 'description',
               existing_type=mysql.VARCHAR(length=250),
               nullable=True)
    op.alter_column('project', 'finish_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('project', 'status',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    op.alter_column('project', 'goals',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    op.alter_column('subtask', 'description',
               existing_type=mysql.VARCHAR(length=250),
               nullable=True)
    op.alter_column('subtask', 'finish_date',
               existing_type=sa.DATE(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('subtask', 'finish_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('subtask', 'description',
               existing_type=mysql.VARCHAR(length=250),
               nullable=False)
    op.alter_column('project', 'goals',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    op.alter_column('project', 'status',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    op.alter_column('project', 'finish_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('project', 'description',
               existing_type=mysql.VARCHAR(length=250),
               nullable=False)
    op.alter_column('project', 'members',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    op.alter_column('profile', 'photo',
               existing_type=mysql.VARCHAR(length=200),
               nullable=False)
    op.alter_column('profile', 'departamento',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    op.alter_column('profile', 'rol',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    op.alter_column('profile', 'description',
               existing_type=mysql.VARCHAR(length=250),
               nullable=False)
    # ### end Alembic commands ###
